// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class EmployeeAvailability
{
    public int EmployeeAvailabilityId { get; set; }

    public string AdloginName { get; set; }

    public decimal MinWeeklyHours { get; set; }

    public decimal MaxWeeklyHours { get; set; }

    public bool IsOpenToOvertime { get; set; }

    public bool IsOpenToVto { get; set; }

    public byte PreferredAlertContactMethodId { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Notes { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<EmployeeAvailabilityDay> EmployeeAvailabilityDays { get; set; } = new List<EmployeeAvailabilityDay>();

    public virtual AlertContactMethod PreferredAlertContactMethod { get; set; }
}