// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class EmployeeAvailabilityDay
{
    public int EmployeeAvailabilityDayId { get; set; }

    public int EmployeeAvailabilityId { get; set; }

    public byte DayOfWeek { get; set; }

    public TimeOnly EarliestStart { get; set; }

    public TimeOnly LatestStop { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public virtual EmployeeAvailability EmployeeAvailability { get; set; }
}