// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class EtimeShift
{
    public int EtimeShiftId { get; set; }

    public int ShiftCodeId { get; set; }

    public string AdloginName { get; set; }

    public string PersonNum { get; set; }

    public string PayGroup { get; set; }

    public int? PayCodeId { get; set; }

    public int? PayCode { get; set; }

    public DateTime ShiftStart { get; set; }

    public DateTime ShiftEnd { get; set; }

    public int BreakMin { get; set; }
}