// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class EtimeShift
{
    public int EtimeShiftId { get; set; }

    public int ShiftCodeId { get; set; }

    public string AdloginName { get; set; }

    public int PersonNum { get; set; }

    public int EmplId { get; set; }

    public int FileNumber { get; set; }

    public string PayGroup { get; set; }

    public int? PayCodeId { get; set; }

    public string PayCode { get; set; }

    public DateTime ShiftStart { get; set; }

    public DateTime ShiftEnd { get; set; }

    public int BreakMin { get; set; }

    public virtual ICollection<TimeOffRequest> TimeOffRequests { get; set; } = new List<TimeOffRequest>();
}