// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class LineAdherence
{
    public int LineAdherenceId { get; set; }

    public string ClientAbbr { get; set; }

    public DateOnly RequiredDate { get; set; }

    public TimeOnly RequiredTime { get; set; }

    public int RequiredHours { get; set; }

    public DateTime InsertedUtcDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public byte[] LastTimestamp { get; set; }
}