// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class ScheduleTemplate
{
    public int ScheduleTemplateId { get; set; }

    public string AdloginName { get; set; }

    public string ExternalMatchId { get; set; }

    public string PayGroup { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ScheduleException> ScheduleExceptions { get; set; } = new List<ScheduleException>();

    public virtual ICollection<ScheduleShiftPattern> ScheduleShiftPatterns { get; set; } = new List<ScheduleShiftPattern>();
}