// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public string Name { get; set; }

    public string Adlogin { get; set; }

    public string ExternalMatchId { get; set; }

    public string PayGroup { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool IsOngoing { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ShiftBreak> ShiftBreaks { get; set; } = new List<ShiftBreak>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();
}