// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class ScheduleShiftPattern
{
    public int ShiftPatternId { get; set; }

    public int ScheduleTemplateId { get; set; }

    public byte DayOfWeek { get; set; }

    public TimeOnly ShiftStartTime { get; set; }

    public TimeOnly ShiftEndTime { get; set; }

    public int BreakMinutes { get; set; }

    public string PayCode { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte ShiftSequence { get; set; }

    public virtual ScheduleTemplate ScheduleTemplate { get; set; }
}