// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class ScheduleException
{
    public int ScheduleExceptionId { get; set; }

    public string AdloginName { get; set; }

    public int ScheduleTemplateId { get; set; }

    public byte ExceptionTypeId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int? TimeOffRequestId { get; set; }

    public string Notes { get; set; }

    public string CreatedBy { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public virtual ScheduleExceptionType ExceptionType { get; set; }

    public virtual ScheduleTemplate ScheduleTemplate { get; set; }

    public virtual ICollection<TimeOffRequest> TimeOffRequests { get; set; } = new List<TimeOffRequest>();
}