// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class Shift
{
    public int ShiftId { get; set; }

    public int ScheduleId { get; set; }

    public string PayCode { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Lasttimestamp { get; set; }

    public virtual Schedule Schedule { get; set; }
}