// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartManagement.Repo.Models;

public partial class SmartOpsContext : DbContext
{
    public SmartOpsContext(DbContextOptions<SmartOpsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AlertContactMethod> AlertContactMethods { get; set; }

    public virtual DbSet<EmployeeAvailability> EmployeeAvailabilities { get; set; }

    public virtual DbSet<EmployeeAvailabilityDay> EmployeeAvailabilityDays { get; set; }

    public virtual DbSet<EtimeShift> EtimeShifts { get; set; }

    public virtual DbSet<Latdetail> Latdetails { get; set; }

    public virtual DbSet<LineAdherence> LineAdherences { get; set; }

    public virtual DbSet<ScheduleException> ScheduleExceptions { get; set; }

    public virtual DbSet<ScheduleExceptionType> ScheduleExceptionTypes { get; set; }

    public virtual DbSet<ScheduleShiftPattern> ScheduleShiftPatterns { get; set; }

    public virtual DbSet<ScheduleTemplate> ScheduleTemplates { get; set; }

    public virtual DbSet<TimeOffRequest> TimeOffRequests { get; set; }

    public virtual DbSet<TimeOffRequestStatus> TimeOffRequestStatuses { get; set; }

    public virtual DbSet<VwCurrentEmployeeAvailability> VwCurrentEmployeeAvailabilities { get; set; }

    public virtual DbSet<WorkGroup> WorkGroups { get; set; }

    public virtual DbSet<WorkGroupMember> WorkGroupMembers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AlertContactMethod>(entity =>
        {
            entity.HasKey(e => e.ContactMethodId);

            entity.ToTable("AlertContactMethod");

            entity.Property(e => e.MethodName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<EmployeeAvailability>(entity =>
        {
            entity.ToTable("EmployeeAvailability");

            entity.HasIndex(e => new { e.AdloginName, e.EffectiveDate, e.EndDate }, "IX_EmployeeAvailability_AdloginName_Dates");

            entity.HasIndex(e => new { e.IsOpenToOvertime, e.EffectiveDate, e.EndDate }, "IX_EmployeeAvailability_OT_Dates");

            entity.HasIndex(e => new { e.IsOpenToVto, e.EffectiveDate, e.EndDate }, "IX_EmployeeAvailability_VTO_Dates");

            entity.HasIndex(e => new { e.AdloginName, e.EffectiveDate }, "UX_EmployeeAvailability_LoginEffDate").IsUnique();

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.EffectiveDate).HasDefaultValueSql("(CONVERT([date],getutcdate()))", "DF_EmployeeAvailability_EffDate");
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_EmployeeAvailability_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_EmployeeAvailability_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.MaxWeeklyHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MinWeeklyHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PreferredAlertContactMethodId).HasDefaultValue((byte)1, "DF_EmployeeAvailability_AlertContact");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.PreferredAlertContactMethod).WithMany(p => p.EmployeeAvailabilities)
                .HasForeignKey(d => d.PreferredAlertContactMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeAvailability_AlertContact");
        });

        modelBuilder.Entity<EmployeeAvailabilityDay>(entity =>
        {
            entity.ToTable("EmployeeAvailabilityDay");

            entity.HasIndex(e => new { e.EmployeeAvailabilityId, e.DayOfWeek }, "IX_EmployeeAvailabilityDay_AvailabilityId");

            entity.HasIndex(e => new { e.EmployeeAvailabilityId, e.DayOfWeek }, "UX_EmployeeAvailabilityDay_DayPerProfile").IsUnique();

            entity.Property(e => e.EarliestStart).HasPrecision(0);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_EmployeeAvailabilityDay_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_EmployeeAvailabilityDay_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.LatestStop).HasPrecision(0);

            entity.HasOne(d => d.EmployeeAvailability).WithMany(p => p.EmployeeAvailabilityDays)
                .HasForeignKey(d => d.EmployeeAvailabilityId)
                .HasConstraintName("FK_EmployeeAvailabilityDay_Availability");
        });

        modelBuilder.Entity<EtimeShift>(entity =>
        {
            entity.HasIndex(e => new { e.AdloginName, e.ShiftStart }, "IX_EtimeShifts_ADLoginName_ShiftStart");

            entity.HasIndex(e => new { e.ShiftStart, e.ShiftEnd }, "IX_EtimeShifts_ShiftStart");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("ADLoginName");
            entity.Property(e => e.PayCode).HasMaxLength(50);
            entity.Property(e => e.PayGroup).HasMaxLength(50);
            entity.Property(e => e.ShiftEnd).HasColumnType("datetime");
            entity.Property(e => e.ShiftStart).HasColumnType("datetime");
        });

        modelBuilder.Entity<Latdetail>(entity =>
        {
            entity.ToTable("LATDetails");

            entity.Property(e => e.LatdetailId).HasColumnName("LATDetailId");
            entity.Property(e => e.CampAbbr).HasMaxLength(10);
            entity.Property(e => e.ClientAbbr)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.InsertedUtcDate).HasColumnType("datetime");
            entity.Property(e => e.LastTimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.LastUpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkGroup).HasMaxLength(50);
        });

        modelBuilder.Entity<LineAdherence>(entity =>
        {
            entity.ToTable("LineAdherence");

            entity.HasIndex(e => new { e.ClientAbbr, e.RequiredDate, e.RequiredTime }, "IX_LineAdherence_ClientAbbr_RequiredDate");

            entity.Property(e => e.ClientAbbr)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.InsertedUtcDate)
                .HasDefaultValueSql("(getutcdate())", "DF_LineAdherence_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastTimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.LastUpdatedDate)
                .HasDefaultValueSql("(getutcdate())", "DF_LineAdherence_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.RequiredTime).HasPrecision(0);
        });

        modelBuilder.Entity<ScheduleException>(entity =>
        {
            entity.ToTable("ScheduleException");

            entity.HasIndex(e => new { e.AdloginName, e.StartDate, e.EndDate }, "IX_ScheduleException_AdloginName_StartDate");

            entity.HasIndex(e => new { e.ScheduleTemplateId, e.StartDate }, "IX_ScheduleException_TemplateId");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ScheduleException_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ScheduleException_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.Notes).HasMaxLength(500);

            entity.HasOne(d => d.ExceptionType).WithMany(p => p.ScheduleExceptions)
                .HasForeignKey(d => d.ExceptionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exception_Type");

            entity.HasOne(d => d.ScheduleTemplate).WithMany(p => p.ScheduleExceptions)
                .HasForeignKey(d => d.ScheduleTemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exception_Template");

            entity.HasOne(d => d.TimeOffRequest).WithMany(p => p.ScheduleExceptions)
                .HasForeignKey(d => d.TimeOffRequestId)
                .HasConstraintName("FK_Exception_TimeOffRequest");
        });

        modelBuilder.Entity<ScheduleExceptionType>(entity =>
        {
            entity.HasKey(e => e.ExceptionTypeId);

            entity.ToTable("ScheduleExceptionType");

            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ScheduleShiftPattern>(entity =>
        {
            entity.HasKey(e => e.ShiftPatternId);

            entity.ToTable("ScheduleShiftPattern");

            entity.HasIndex(e => new { e.ScheduleTemplateId, e.DayOfWeek, e.ShiftSequence }, "UX_ShiftPattern_DaySeqPerTemplate").IsUnique();

            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ShiftPattern_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ShiftPattern_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.PayCode).HasMaxLength(50);
            entity.Property(e => e.ShiftEndTime).HasPrecision(0);
            entity.Property(e => e.ShiftSequence).HasDefaultValue((byte)1, "DF_ShiftPattern_Sequence");
            entity.Property(e => e.ShiftStartTime).HasPrecision(0);

            entity.HasOne(d => d.ScheduleTemplate).WithMany(p => p.ScheduleShiftPatterns)
                .HasForeignKey(d => d.ScheduleTemplateId)
                .HasConstraintName("FK_ShiftPattern_Template");
        });

        modelBuilder.Entity<ScheduleTemplate>(entity =>
        {
            entity.ToTable("ScheduleTemplate");

            entity.HasIndex(e => new { e.AdloginName, e.EffectiveDate }, "IX_ScheduleTemplate_AdloginName_EffectiveDate");

            entity.HasIndex(e => e.AdloginName, "UX_ScheduleTemplate_OneActivePerEmployee")
                .IsUnique()
                .HasFilter("([EndDate] IS NULL)");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ExternalMatchId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ScheduleTemplate_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_ScheduleTemplate_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.PayGroup)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<TimeOffRequest>(entity =>
        {
            entity.ToTable("TimeOffRequest");

            entity.HasIndex(e => new { e.AdloginName, e.StartDate, e.EndDate }, "IX_TimeOffRequest_AdloginName_StartDate");

            entity.HasIndex(e => new { e.AdloginName, e.StatusId }, "IX_TimeOffRequest_AdloginName_StatusId");

            entity.HasIndex(e => new { e.StatusId, e.StartDate }, "IX_TimeOffRequest_StatusId_StartDate");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_TimeOffRequest_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_TimeOffRequest_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.RequestedOn)
                .HasDefaultValueSql("(getutcdate())", "DF_TimeOffRequest_RequestedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.ReviewNotes).HasMaxLength(500);
            entity.Property(e => e.ReviewedBy).HasMaxLength(100);
            entity.Property(e => e.ReviewedOn).HasColumnType("datetime");
            entity.Property(e => e.StatusId).HasDefaultValue((byte)1, "DF_TimeOffRequest_Status");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.ScheduleException).WithMany(p => p.TimeOffRequests)
                .HasForeignKey(d => d.ScheduleExceptionId)
                .HasConstraintName("FK_TimeOffRequest_ScheduleException");

            entity.HasOne(d => d.Status).WithMany(p => p.TimeOffRequests)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeOffRequest_Status");
        });

        modelBuilder.Entity<TimeOffRequestStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.ToTable("TimeOffRequestStatus");

            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<VwCurrentEmployeeAvailability>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_CurrentEmployeeAvailability");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaxWeeklyHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MinWeeklyHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PreferredAlertMethod)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<WorkGroup>(entity =>
        {
            entity.ToTable("WorkGroup");

            entity.HasIndex(e => e.Name, "UX_WorkGroup_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_WorkGroup_Inserted")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_WorkGroup_IsActive");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_WorkGroup_Updated")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<WorkGroupMember>(entity =>
        {
            entity.ToTable("WorkGroupMember");

            entity.HasIndex(e => e.AdloginName, "IX_WorkGroupMember_AdloginName_Active").HasFilter("([RemovedDateUtc] IS NULL)");

            entity.HasIndex(e => e.WorkGroupId, "IX_WorkGroupMember_WorkGroupId_Active").HasFilter("([RemovedDateUtc] IS NULL)");

            entity.HasIndex(e => new { e.WorkGroupId, e.AdloginName }, "UX_WorkGroupMember_ActivePerGroup")
                .IsUnique()
                .HasFilter("([RemovedDateUtc] IS NULL)");

            entity.Property(e => e.AddedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.AddedDateUtc)
                .HasDefaultValueSql("(getutcdate())", "DF_WorkGroupMember_Added")
                .HasColumnType("datetime");
            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RemovedBy).HasMaxLength(100);
            entity.Property(e => e.RemovedDateUtc).HasColumnType("datetime");

            entity.HasOne(d => d.WorkGroup).WithMany(p => p.WorkGroupMembers)
                .HasForeignKey(d => d.WorkGroupId)
                .HasConstraintName("FK_WorkGroupMember_Group");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}