// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartManagement.Repo.Models;

public partial class SmartOpsContext : DbContext
{
    public SmartOpsContext(DbContextOptions<SmartOpsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Latdetail> Latdetails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Latdetail>(entity =>
        {
            entity.ToTable("LATDetails");

            entity.Property(e => e.LatdetailId).HasColumnName("LATDetailId");
            entity.Property(e => e.CampAbbr).HasMaxLength(10);
            entity.Property(e => e.ClientAbbr)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.InsertedUtcDate).HasColumnType("datetime");
            entity.Property(e => e.LastTimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.LastUpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkGroup).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}