// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartManagement.Repo.Models;

public partial class SmartOpsContext : DbContext
{
    public SmartOpsContext(DbContextOptions<SmartOpsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EtimeShift> EtimeShifts { get; set; }

    public virtual DbSet<LineAdherence> LineAdherences { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<ShiftBreak> ShiftBreaks { get; set; }

    public virtual DbSet<TimeOffRequest> TimeOffRequests { get; set; }

    public virtual DbSet<TimeOffRequestStatus> TimeOffRequestStatuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EtimeShift>(entity =>
        {
            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("ADLoginName");
            entity.Property(e => e.PayCode).HasMaxLength(50);
            entity.Property(e => e.PayGroup).HasMaxLength(50);
            entity.Property(e => e.ShiftEnd).HasColumnType("datetime");
            entity.Property(e => e.ShiftStart).HasColumnType("datetime");
        });

        modelBuilder.Entity<LineAdherence>(entity =>
        {
            entity.HasKey(e => e.LineAdherenceId).HasName("PK_LineAdherence");

            entity.Property(e => e.ClientAbbr)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.InsertedUtcDate).HasColumnType("datetime");
            entity.Property(e => e.LastTimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.LastUpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.Property(e => e.Adlogin)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("ADLogin");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.ExternalMatchId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.InsertedDateUtc).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PayGroup)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.InsertedDateUtc).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc).HasColumnType("datetime");
            entity.Property(e => e.Lasttimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.PayCode).HasMaxLength(50);
            entity.Property(e => e.StartTime).HasColumnType("datetime");

            entity.HasOne(d => d.Schedule).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_Schedules");
        });

        modelBuilder.Entity<ShiftBreak>(entity =>
        {
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.InsertedDateUtc).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc).HasColumnType("datetime");
            entity.Property(e => e.Lasttimestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.StartTime).HasColumnType("datetime");

            entity.HasOne(d => d.Schedule).WithMany(p => p.ShiftBreaks)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShiftBreaks_Schedules");
        });

        modelBuilder.Entity<TimeOffRequest>(entity =>
        {
            entity.ToTable("TimeOffRequest");

            entity.HasIndex(e => new { e.AdloginName, e.StatusId }, "IX_TimeOffRequest_AdloginName_StatusId");

            entity.HasIndex(e => new { e.StatusId, e.ShiftStart }, "IX_TimeOffRequest_StatusId_ShiftStart");

            entity.HasIndex(e => new { e.EtimeShiftId, e.AdloginName }, "UX_TimeOffRequest_ShiftId_AdloginName_Active")
                .IsUnique()
                .HasFilter("([StatusId]<>(3) AND [StatusId]<>(4))");

            entity.Property(e => e.AdloginName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InsertedDateUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.RequestedOn)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ReviewNotes).HasMaxLength(500);
            entity.Property(e => e.ReviewedBy).HasMaxLength(100);
            entity.Property(e => e.ReviewedOn).HasColumnType("datetime");
            entity.Property(e => e.ScheduleUpdatedBy).HasMaxLength(100);
            entity.Property(e => e.ScheduleUpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.ShiftEnd).HasColumnType("datetime");
            entity.Property(e => e.ShiftStart).HasColumnType("datetime");
            entity.Property(e => e.StatusId).HasDefaultValue((byte)1);
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.EtimeShift).WithMany(p => p.TimeOffRequests)
                .HasForeignKey(d => d.EtimeShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeOffRequest_EtimeShift");

            entity.HasOne(d => d.Status).WithMany(p => p.TimeOffRequests)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeOffRequest_Status");
        });

        modelBuilder.Entity<TimeOffRequestStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.ToTable("TimeOffRequestStatus");

            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}