// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class TimeOffRequest
{
    public int TimeOffRequestId { get; set; }

    public string AdloginName { get; set; }

    public int EtimeShiftId { get; set; }

    public DateTime ShiftStart { get; set; }

    public DateTime ShiftEnd { get; set; }

    public string Reason { get; set; }

    public byte StatusId { get; set; }

    public DateTime RequestedOn { get; set; }

    public string ReviewedBy { get; set; }

    public DateTime? ReviewedOn { get; set; }

    public string ReviewNotes { get; set; }

    public bool ScheduleUpdated { get; set; }

    public DateTime? ScheduleUpdatedOn { get; set; }

    public string ScheduleUpdatedBy { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual EtimeShift EtimeShift { get; set; }

    public virtual TimeOffRequestStatus Status { get; set; }
}