// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class TimeOffRequest
{
    public int TimeOffRequestId { get; set; }

    public string AdloginName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Reason { get; set; }

    public byte StatusId { get; set; }

    public DateTime RequestedOn { get; set; }

    public string ReviewedBy { get; set; }

    public DateTime? ReviewedOn { get; set; }

    public string ReviewNotes { get; set; }

    public int? ScheduleExceptionId { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ScheduleException ScheduleException { get; set; }

    public virtual ICollection<ScheduleException> ScheduleExceptions { get; set; } = new List<ScheduleException>();

    public virtual TimeOffRequestStatus Status { get; set; }
}