// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class VwCurrentEmployeeAvailability
{
    public int EmployeeAvailabilityId { get; set; }

    public string AdloginName { get; set; }

    public decimal MinWeeklyHours { get; set; }

    public decimal MaxWeeklyHours { get; set; }

    public bool IsOpenToOvertime { get; set; }

    public bool IsOpenToVto { get; set; }

    public string PreferredAlertMethod { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Notes { get; set; }
}