// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartManagement.Repo.Models;

public partial class WorkGroup
{
    public int WorkGroupId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime InsertedDateUtc { get; set; }

    public DateTime LastUpdatedUtc { get; set; }

    public virtual ICollection<WorkGroupMember> WorkGroupMembers { get; set; } = new List<WorkGroupMember>();
}
