// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace SmartManagement.Repo.Models;

public partial class WorkGroupMember
{
    public int WorkGroupMemberId { get; set; }

    public int WorkGroupId { get; set; }

    public string AdloginName { get; set; }

    public DateTime AddedDateUtc { get; set; }

    public DateTime? RemovedDateUtc { get; set; }

    public string AddedBy { get; set; }

    public string RemovedBy { get; set; }

    public virtual WorkGroup WorkGroup { get; set; }
}
